local prettier = require("prettier")

vim.keymap.set("n", "<leader>f", prettier.format, { buffer = true })

prettier.setup({
  -- prettier options
  single_quote = false,
  tab_width = 2,
  use_tabs = false,
  semi = true,
  trailing_comma = "all",
  config_precedence = "file-override",
  bracket_spacing = true,
  arrow_parens = "always",
  end_of_line = "lf",
  embedded_language_formatting = "auto",
  html_whitespace_sensitivity = "css",
  jsx_bracket_same_line = false,
  jsx_single_quote = false,
  print_width = 80,
  prose_wrap = "preserve",
  quote_props = "as-needed",
  range_end = -1,
  range_start = 0,
  require_pragma = false,
  prose_wrap = "preserve",
  use_editorconfig = false,
  -- prettier specific filetypes
  filetypes = {
      "javascript",
      "javascriptreact",
      "typescript",
      "typescriptreact",
      "css",
      "scss",
      "json",
      "graphql",
      "markdown",
      "vue",
      "html",
      "yaml",
      "svelte",
      "lua",
      "ruby",
      "erb",
      "ejs",
      "handlebars",
      "php",
      "twig",
      "python",
      "java",
      "kotlin",
      "scala",
      "swift",
      "c",
      "cpp",
      "rust",
      "go",
      "dart",
      "elixir",
      "elm",
      "haskell",
      "julia",
      "ocaml",
      "perl",
      "r",
      "reason",
      "shell",
      "sql",
      "vim",
      "yaml",
      "markdown",
      "json",
      "jsonc",
      "json5",
  }})
